apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-api
  labels:
    app: synergychat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-api
  template:
    metadata:
      labels:
        app: synergychat-api
    spec:
      volumes:
        - name: synergychat-api-volume
          persistentVolumeClaim:
            claimName: synergychat-api-pvc
      containers:
      - name: synergychat-api
        image: bootdotdev/synergychat-api:latest
        env:
          # Define the environment variable
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: synergychat-api-configmap  # The ConfigMap this value comes from
                key: API_PORT  # The key to fetch
          - name: API_DB_FILEPATH
            valueFrom:
              configMapKeyRef:
                name: synergychat-api-configmap  # The ConfigMap this value comes from
                key: API_DB_FILEPATH  # The key to fetch
          - name: CRAWLER_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: synergychat-api-configmap  # The ConfigMap this value comes from
                key: CRAWLER_BASE_URL  # The key to fetch
        volumeMounts:
          - name: synergychat-api-volume
            mountPath: /persist